// Generated by scripts/prepare-assets.mjs when the suite graphics change.
const suiteImageUrls = {"zh":"./assets/AivaraSuite_中文.svg?v=835e159f377491f9","en":"./assets/AivaraSuite_English.svg?v=fa2448fdef5b08ce"};

const translations = {
  zh: {
    homeLabel: 'Aivara 首页', navLabel: '主导航', workflowLabel: 'AivaraSuite 影像分析流程', productsLabel: 'Aivara 产品模块',
    assistantNav: 'AivaraAgent', assistantTitle: '与 AivaraAgent 对话', assistantDescription: '您的专属智能工作空间',
    openBio: '打开 AivaraBio', suiteBioLink: '在 AivaraBio 中上传文件并查看三维结构', bioKicker: '交互式研究工具',
    bioDescription: '在浏览器中查看蛋白质三维结构，准备结构预测与结合验证、小型蛋白设计任务，并审阅结果。使用现有 Aivara 账户登录。',
    bioNote: '仅供研究使用。任务由用户明确提交，结果需专业复核。',
    title: 'AivaraSuite | 影像分析与分子研究', description: 'AivaraSuite 连接核医学影像分析与分子研究：影像查看、定量、临床复核、蛋白质结构可视化、预测与设计。',
    skip: '跳转至内容', navSuite: '套件', navSolutions: '产品', heroTitle: '让核医学影像分析<br><em>更加清晰、连贯</em>',
    heroBody: '从核医学影像分析到蛋白质结构可视化、预测与设计，AivaraSuite 连接临床分析与分子研究。',
    exploreSuite: '了解 AivaraSuite', heroBottom: '精准影像 · 协同分析', suiteKicker: '统一工作流程',
    suiteIntro: '整合 AivaraOnco、AivaraDosimetry、AivaraCardio、AivaraNeuro 与 AivaraBio，覆盖核医学影像分析与蛋白质结构研究。',
    step1: '影像查看', step2: '配准与融合', step3: '分割', step4: '定量', step5: '临床复核与报告',
    solutionsKicker: '应用方向', solutionsTitle: '面向临床分析与分子研究的产品模块', solutionsIntro: '查看五个模块的影像与结构示例，以及各自的主要工作流程。',
    footerText: '影像分析与分子研究软件', backTop: '返回顶部 ↑',
    suiteAlt: 'AivaraSuite 五个模块：AivaraOnco、AivaraDosimetry、AivaraCardio、AivaraNeuro、AivaraBio', productAlt: (name) => `${name} 影像分析示例`
  },
  en: {
    homeLabel: 'Aivara home', navLabel: 'Primary navigation', workflowLabel: 'AivaraSuite imaging workflow', productsLabel: 'Aivara products',
    assistantNav: 'AivaraAgent', assistantTitle: 'Talk to AivaraAgent', assistantDescription: 'Your private intelligent workspace',
    openBio: 'Open AivaraBio', suiteBioLink: 'Upload and explore 3D structures in AivaraBio', bioKicker: 'Interactive research tools',
    bioDescription: 'Explore protein structures, prepare computational structure and binding validation or mini-protein design jobs, and review results in your browser. Sign in with your existing Aivara account.',
    bioNote: 'For research use only. Jobs require explicit submission; results require expert review.',
    title: 'AivaraSuite | Imaging & Molecular Research', description: 'AivaraSuite connects nuclear medicine imaging and molecular research: image analysis, clinical review, protein structure visualization, prediction and design.',
    skip: 'Skip to content', navSuite: 'Suite', navSolutions: 'Solutions', heroTitle: 'Nuclear medicine,<br><em>clearly connected</em>',
    heroBody: 'From nuclear medicine image analysis to protein structure visualization, prediction and design, AivaraSuite connects clinical analysis and molecular research.',
    exploreSuite: 'Explore AivaraSuite', heroBottom: 'Precision imaging · Connected analysis', suiteKicker: 'One connected workflow',
    suiteIntro: 'Onco, Dosimetry, Cardio, Neuro and Bio: connected tools for image viewing, quantification, clinical review, protein structures, prediction and design.',
    step1: 'Image viewing', step2: 'Registration & fusion', step3: 'Segmentation', step4: 'Quantification', step5: 'Clinical review & report',
    solutionsKicker: 'Applications', solutionsTitle: 'A suite for clinical analysis & molecular research', solutionsIntro: 'Explore imaging and structure examples, and the main workflows of all five modules.',
    footerText: 'Imaging & molecular research software', backTop: 'Back to top ↑',
    suiteAlt: 'AivaraSuite: Onco, Dosimetry, Cardio, Neuro and Bio', productAlt: (name) => `${name} imaging analysis example`
  }
};

const products = {
  onco: { name: 'Onco', index: '01', accent: '#f37436', file: 'AivaraOnco', zh: { summary: '多示踪剂影像融合、病灶定量与纵向随访。', features: ['PSMA / FDG 多示踪剂融合对比', '可供临床编辑的辅助分割', '病灶定量分析与治疗反应可视化'] }, en: { summary: 'Multi-tracer image fusion, lesion quantification, and longitudinal follow-up.', features: ['PSMA / FDG fusion comparison', 'Clinically editable assisted segmentation', 'Lesion quantification and therapy response visualization'] } },
  dose: { name: 'Dosimetry', index: '02', accent: '#a947e9', file: 'AivaraDosimetry', zh: { summary: '连接多时间点影像处理与吸收剂量评估。', features: ['多时间点影像配准', '器官与靶区分割及临床复核', '时间-活度曲线、吸收剂量与报告'] }, en: { summary: 'From multi-timepoint imaging to absorbed dose assessment.', features: ['Multi-timepoint image registration', 'Organ and target segmentation with clinician review', 'Time–activity curves, absorbed dose, and reporting'] } },
  cardio: { name: 'Cardio', index: '03', accent: '#ed433a', file: 'AivaraCardio', zh: { summary: '面向心血管影像的分割、摄取评估与区域定量。', features: ['主动脉辅助分割', '血管摄取评估', '全主动脉及区域定量分析'] }, en: { summary: 'Segmentation, uptake assessment, and regional quantification for cardiovascular imaging.', features: ['Assisted aortic segmentation', 'Vascular uptake assessment', 'Whole-aorta and regional quantification'] } },
  neuro: { name: 'Neuro', index: '04', accent: '#17a9bc', file: 'AivaraNeuro', zh: { summary: '融合 PET/MR 影像，支持脑区分割与参考区定量。', features: ['PET/MR 三平面融合', '脑区自动分割', 'SUVR 参考区定量与三维皮层分区'] }, en: { summary: 'PET/MR fusion, brain segmentation, and reference-region quantification.', features: ['PET/MR tri-modal fusion', 'Brain region segmentation', 'SUVR reference-region analysis and 3D cortical parcellation'] } },
  bio: { name: 'Bio', index: '05', accent: '#159451', image: 'aivara-bio-structure.svg', zh: { summary: '上传 PDB 或 mmCIF 结构文件，即可在浏览器中交互式查看三维分子结构，并进行蛋白质结构预测与设计。', features: ['旋转、缩放三维结构，查看分子链信息', '结构预测与结合验证、小型蛋白设计框架', '查看任务进度，导出结构与结果；使用现有 Aivara 账户登录'] }, en: { summary: 'Upload PDB / mmCIF files, explore interactive 3D structures, and work on protein prediction and design.', features: ['Rotate, zoom and explore molecular structures and chains', 'Structure & Binding Validation and Mini-Protein Design Framework', 'Job status, structures and result exports with your Aivara account'] } }
};

let language = localStorage.getItem('aivara-language') === 'en' ? 'en' : 'zh';
let activeProduct = 'onco';

function renderProduct() {
  const product = products[activeProduct];
  const copy = product[language];
  const suffix = language === 'zh' ? '中文' : 'English';
  document.getElementById('product-index').textContent = product.index;
  const title = document.getElementById('product-title');
  title.innerHTML = `Aivara<span>${product.name}</span>`;
  title.style.setProperty('--accent', product.accent);
  document.getElementById('product-summary').textContent = copy.summary;
  const list = document.getElementById('product-features');
  list.innerHTML = copy.features.map((feature) => `<li>${feature}</li>`).join('');
  list.style.setProperty('--accent', product.accent);
  const image = document.getElementById('product-image');
  image.src = product.image ? `./assets/${product.image}` : `./assets/${product.file}_${suffix}.webp`;
  image.width = product.image ? 860 : 1672;
  image.height = product.image ? 670 : 941;
  document.getElementById('product-logo').hidden = activeProduct !== 'bio';
  document.getElementById('product-open').hidden = activeProduct !== 'bio';
  image.alt = activeProduct === 'bio' ? (language === 'zh' ? 'AivaraBio 蛋白质三维结构示例' : 'AivaraBio 3D protein structure example') : translations[language].productAlt(`Aivara${product.name}`);
  document.querySelectorAll('.solution-tab').forEach((button) => {
    const selected = button.dataset.product === activeProduct;
    button.classList.toggle('active', selected);
    button.setAttribute('aria-selected', String(selected));
    button.tabIndex = selected ? 0 : -1;
  });
}

function renderLanguage() {
  const copy = translations[language];
  document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
  document.title = copy.title;
  document.querySelector('meta[name="description"]').content = copy.description;
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    element.innerHTML = copy[element.dataset.i18n];
  });
  document.querySelectorAll('[data-i18n-aria]').forEach((element) => {
    element.setAttribute('aria-label', copy[element.dataset.i18nAria]);
  });
  document.getElementById('suite-image').src = suiteImageUrls[language];
  document.getElementById('suite-image').alt = copy.suiteAlt;
  document.querySelectorAll('[data-lang]').forEach((button) => {
    const selected = button.dataset.lang === language;
    button.classList.toggle('active', selected);
    button.setAttribute('aria-pressed', String(selected));
  });
  renderProduct();
}

document.querySelectorAll('[data-lang]').forEach((button) => button.addEventListener('click', () => {
  language = button.dataset.lang;
  localStorage.setItem('aivara-language', language);
  renderLanguage();
}));
document.querySelectorAll('[data-product]').forEach((button) => button.addEventListener('click', () => {
  activeProduct = button.dataset.product;
  renderProduct();
}));
document.querySelector('.solution-tabs').addEventListener('keydown', (event) => {
  if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return;
  event.preventDefault();
  const keys = Object.keys(products);
  let index = keys.indexOf(activeProduct);
  if (event.key === 'ArrowRight') index = (index + 1) % keys.length;
  if (event.key === 'ArrowLeft') index = (index - 1 + keys.length) % keys.length;
  if (event.key === 'Home') index = 0;
  if (event.key === 'End') index = keys.length - 1;
  activeProduct = keys[index];
  renderProduct();
  document.querySelector(`[data-product="${activeProduct}"]`).focus();
});
renderLanguage();
